### ISSUE TITLE
errors from protoc --proto_path=. --go_out=. --gorm_out=. proto/product/product.proto

### ISSUE THREAD

**Issue by goodforever** [infobloxopen/protoc-gen-gorm#126]
Run 
protoc --proto_path=. --go_out=. --gorm_out=. proto/product/product.proto

Then got errors 

github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto: File not found.
github.com/infobloxopen/atlas-app-toolkit/query/collection_operators.proto: File not found.
proto/product/product.proto: Import "github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto" was not found or had errors.
proto/product/product.proto: Import "github.com/infobloxopen/atlas-app-toolkit/query/collection_operators.proto" was not found or had errors.
proto/product/product.proto:38:5: "infoblox.api.FieldSelection" is not defined.
proto/product/product.proto:83:5: "infoblox.api.Filtering" is not defined.
proto/product/product.proto:84:5: "infoblox.api.Sorting" is not defined.
proto/product/product.proto:85:5: "infoblox.api.FieldSelection" is not defined.
proto/product/product.proto:86:5: "infoblox.api.Pagination" is not defined.

In fact 
github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto: File not found.  and 
github.com/infobloxopen/atlas-app-toolkit/query/collection_operators.proto:
are exist

**Comment by dkukharau** [comment]
Hi!
You can try to follow our [example](https://github.com/infobloxopen/protoc-gen-gorm/blob/master/Makefile#L45) on how to setup protobuf include/output paths correctly. It's true that it's interface is not too user-friendly.

**Comment by Calebjh** [comment]
Hey @goodforever, thanks for your interest in this project.
As Daniil said, this sounds like a general protoc imports problem. Were you able to resolve it yet?

**Comment by nof20** [comment]
Anyone else having the same problem and find this from a web search - the solution is to explicitly import GORM's protos to `protoc`, e.g.: `protoc -I. -I$GOPATH/src --go_out=<your code directory> --gorm_out="engine=mysql:..<your code directory>" your.proto`

**Comment by goldsky** [comment]
This is my solution:

1. copy [gorm.proto](https://github.com/infobloxopen/protoc-gen-gorm/blob/main/proto/options/gorm.proto) file into project's root folder, eg: [my_awesome_project_root/]**gorm/proto/options/gorm.proto**
2. In the proto file:
```proto
syntax = "proto3";
package product;
import "gorm.proto";
option go_package = "./proto/product";

message Product {
	option (gorm.opts).ormable = true;
	uint64 id = 1;
	// ...
}
```
3. run `protoc` from my awesome project root folder
```shell
protoc --proto_path=. \
	--proto_path=./gorm/proto/options \
	--go_out=:. \
	--gorm_out="engine=postgres:." \
	./proto/product/product.proto
```
