### ISSUE TITLE
Sharing "gormable" protobuf between several project in different programming languages.

### ISSUE THREAD

**Issue by amricko0b** [infobloxopen/protoc-gen-gorm#130]
Greetings!

Let's say, I have following *.proto:

```
syntax = "proto3";

package proto;
option go_package = "github.com/amricko0b/prototest";

import "github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto";

message Account {
    uint64 id = 1;
    string number = 2;
    double available = 10;
    double reserve = 11;
    string version = 12;
    string state = 13;
    option (gorm.opts) = {
        ormable: true
    };
}

```

For case of generating Golang code everything works fine. But what if I try to generate code for some other languages? When I do this for TypeScript (using protoc-gen-ts), I obviously get "Import was not found" error for file gorm.proto.

What should I do to keep my protobuf language-independent and still save gorm support?

**Comment by dkukharau** [comment]
Hi @amricko0b !
From the protoc compiler perspective you just need to make sure that `github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto` exists in one of the include paths(passed with `-I` flag to protoc), and it should work for any language.
It's up to you how you'd like to achieve this: at least you can create a `proto` directory under your TypeScript project and put `gorm.proto` under `ts_project_root/proto/github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto` and pass `-I./proto` option to protoc when you generate your TS code.

**Comment by amricko0b** [comment]
Thanks for clarity! I think this will do.
Issue may be closed now.
