### ISSUE TITLE
"to" mappings for StringArrays

### ISSUE THREAD

**Issue by chrusty** [infobloxopen/protoc-gen-gorm#140]
I'm working on a project where I want to store string-arrays in Postgres. The proto-generation mostly works, but don't result in any mappings for the arrays.

The generated gorm.pb files end up containing `// Repeated type []string is not an ORMable message type`. Instead I want them to have something like this:

```
       for _, v := range m.SomeStringArray{
               to.SomeStringArray = append(to.SomeStringArray, v)
       }
```

I've forked and make a [working example](https://github.com/infobloxopen/protoc-gen-gorm/compare/master...SplunkCloud:to_mapping_for_string_arrays?expand=1), but this is kinda hard-coded (and its highly possible that I'm missing the point).

Let me know if this sounds like something you'd be interested in, and we can discuss the cleanest way to implement it. Obviously there are other types of array handled by github.com/lib/pq too.

**Comment by dkukharau** [comment]
Hello!
Thanks for you interest in the project! It's definitely useful to add support of postgres arrays and it would be great if you wanted to contribute with this.
To my current feeling you would need the following to implement this feature:
1.  Extend GORM model generation to support `repeated string` protobuf type and generate `pq.StringArray` field in associated GORM model.
2. Add support of protobuf <-> GORM(to/from) conversion for this type.
3. Extend examples with the usage of this type to show that it's actually working.
4. This functionality should be generated only if --gorm_out="engine=postgres" flag is passed.

You can look at the implementation of `Jsonb` postgres type as an example, adding support of `pq.StringArray` should be very similar.

Feel free to ask any questions if something is unclear!

**Comment by Calebjh** [comment]
Ah yes, this is (was?) somewhere on my to-do list of improvements...

The Jsonb type was partially meant as a stopgap for this use-case, but for Postgres at least I did want to include support for the array types eventually. 
I think all of the special types are Postgres specific right now, so I'm with @dkukharau on the list of requirements.

**Comment by chrusty** [comment]
OK, I've got a PR ready here: https://github.com/infobloxopen/protoc-gen-gorm/pull/150

**Comment by dkukharau** [comment]
hey @chrusty !
Sorry for not responding for a long time. Yes, we're extremely interested in unit tests, so it would be great if you have a chance to help us with them(at least demonstrate some patterns you used).

**Comment by chrusty** [comment]
Alright, I'll set something up in a new PR.

**Comment by Calebjh** [comment]
Unit tests are a different issue. I'm closing this issue since your PR is now merged. Thanks for your contribution!
