### ISSUE TITLE
Readonly fields?

### ISSUE THREAD

**Issue by molon** [infobloxopen/protoc-gen-gorm#144]
There are readonly fields many time.
```
message Shop {
    option (gorm.opts) = {
        ormable: true,
        multi_account: true,
        include: [
            {type: "*time.Time", name: "deleted_at"} // this field is non-visible. it's ok.
        ]
    };

    string name = 4;

    // We want the fields below to be visible, but can't writable.
    string id = 1 [(gorm.field).tag = {primary_key: true}]; 
    google.protobuf.Timestamp created_at = 2;
    google.protobuf.Timestamp updated_at = 3;
}
```
I have tried this library. https://github.com/infobloxopen/protoc-gen-atlas-validate
Then I cant assign the `created_at` field in `request.payload`.
But~ the `created_at` was still be updated to empty. 
Because If I don't assign the `created_at` field, it will be transfer into request as empty value.

**Comment by molon** [comment]
And sometimes we need write-only fields. eg: `password`

**Comment by molon** [comment]
with the first question, I have used `protoc-gen-atlas-validate` and `field_presence` to solve it.
But I disable the `FieldMasks` for gateway to prevent wrong usage(https://github.com/agilab/atlas-app-toolkit/commit/c2a67b5120c88db3acb51181a4021fcfd18579b3).

**Comment by fi0** [comment]
@molon how did you create a password field? and probably the password_hash field?
