### ISSUE TITLE
Time type managing 

### ISSUE THREAD

**Issue by YReshetko** [infobloxopen/protoc-gen-gorm#159]
Hi Infoblox Team. 

Could you advise if the plugin supports Time type for postgress (not timestamp or date).
When I use regular `google.protobuf.Timestamp` the time is  casted to `time.Time` as `0000-00-00Thh:mm:ss` and this is a problem.

Thanks in advance for your answer.

**Comment by Calebjh** [comment]
I don't have time to investigate this thoroughly just now, but I suspect this will be a limitation. This is a little old, but it looks like GORM may only support the one type of Postgres time object https://stackoverflow.com/a/39519483

**Comment by YReshetko** [comment]
Thanks @Calebjh for your answer.
I'm aware about the limitation, but I thought that you have some workaround for that.

I would like to ask you to have a look at next PR:
https://github.com/infobloxopen/protoc-gen-gorm/pull/160

This change supports Time type at least at ORM mapping and unmarshaling steps with limited time format, but I think it's enough for now in my project. 
Obviously I could validate the time inside my code, but I think, as I start to use your nice tool it would be better to have the validation in generated code.

Thanks again and best regards.
