### ISSUE TITLE
How to set the table name as singular

### ISSUE THREAD

**Issue by job2wd** [infobloxopen/protoc-gen-gorm#186]
How to set the table name as singular

**Comment by Calebjh** [comment]
There is an option https://github.com/infobloxopen/protoc-gen-gorm/blob/master/options/gorm.proto#L27 that can be set on the message to specify the table name (ex. https://github.com/infobloxopen/protoc-gen-gorm/blob/master/example/feature_demo/demo_types.proto#L24). It just generates the GORM `TableName` function, so you can also define that function manually in the generated code package. You may also be able to change that for the whole application using the GORM `SingularTable` function (https://godoc.org/github.com/jinzhu/gorm#DB.SingularTable)
