### ISSUE TITLE
#181 migrates github.com/golang/protobuf from v0.0.0-20180706225418-1325a051a275 -> v1.3.1 but doesn't using gogo/protobuf require us to also use github.com/golang/protobuf with v1.0.0?

### ISSUE THREAD

**Issue by daodennis** [infobloxopen/protoc-gen-gorm#191]
Hi,

I was under the impression that the version of `gogo/protobuf` must match for build and runtime dependencies

In this PR #181 the version was updated and I'm wondering if that potentially breaks projects that try to use gorm and the protogen-go-gorm compiler?  For instance the release notes of gogo/protbuf https://github.com/gogo/protobuf/releases/tag/v1.0.0

> This is the first tag of golang/protobuf and gogo/protobuf is syncing with this process.
This release also includes:
minor fixes
compatibility with go 1.10 beta
compatibility with protoc 3.5.1

**Comment by Calebjh** [comment]
The code generated by the protoc-gen-gorm plugin shouldn't actually have a runtime dependency on the `gogo/protobuf` package. If a custom type is used from this repo (like the Inet proto type) the package will probably be imported, which could muddle the dependencies though.

**Comment by daodennis** [comment]
Thanks for the feedback Calebjh!
