### ISSUE TITLE
transaction handling in default methods

### ISSUE THREAD

**Issue by johnbelamaric** [infobloxopen/protoc-gen-gorm#37]
For default methods that deal with association updates, we are currently doing the transaction handling inside the method. See, for example: https://github.com/infobloxopen/atlas-contacts-app/blob/master/pb/contacts/contacts.pb.gorm.go#L163

This means that that method cannot be re-used in a hand-written method. Instead, we should move that transaction handling out to the caller of the default method.

**Comment by Calebjh** [comment]
This was noticed as probably problematic earlier and removed with other improvements to that generated function in #14. This happened right after the 0.1.0 release, but should be included in 0.2.0.

**Comment by johnbelamaric** [comment]
Awesome.
