### ISSUE TITLE
Error on import message, is not ormable.

### ISSUE THREAD

**Issue by serkulesh** [infobloxopen/protoc-gen-gorm#68]
When import another proto file **import "color/color_service.proto"** and try to use message with "**option (gorm.opts) = {ormable: true}**", i got an error: "error:color.Color is not ormable.".

color_service.proto
```
message Color {
    option (gorm.opts) = {ormable: true};
    string name = 1;
}
```

part_service.proto
```
import "options/gorm.proto";
import "color/color_service.proto";
message Part {
    option (gorm.opts) = {ormable: true};
    string name = 1;
    int32 status = 2;
    color.Color color = 3;
}
```

**Comment by Calebjh** [comment]
Just to check, are color_service.proto and part_service.proto in the same package/folder, or different folders?
