### ISSUE TITLE
Generated code does not compile with ApplyCollectionOperators error.

### ISSUE THREAD

**Issue by majelbstoat** [infobloxopen/protoc-gen-gorm#86]
This looks really promising, thanks for releasing it :) Noticing the following compile error for a simple ormable message:

```
events.pb.gorm.go:190:42: not enough arguments in call to "vendor/github.com/infobloxopen/atlas-app-toolkit/gorm".ApplyCollectionOperators
have (*"vendor/github.com/jinzhu/gorm".DB, *query.Filtering, *query.Sorting, *query.Pagination, *query.FieldSelection)
want (*"vendor/github.com/jinzhu/gorm".DB, interface {}, *query.Filtering, *query.Sorting, *query.Pagination, *query.FieldSelection)
```

Message looks like this:
```proto
message AccountCreatedEvent {
	option (gorm.opts).ormable = true;
	string user_id = 1;
}
```

Relevant generated code looks like this:
```go
	ormResponse := []AccountCreatedEventORM{}
	f, s, p, fs, err := getCollectionOperators(req)
	if err != nil {
		return nil, err
	}
	db, err = gorm2.ApplyCollectionOperators(db, f, s, p, fs) // Missing obj parameter here.
```

**Comment by Calebjh** [comment]
Thanks for noticing our project and this bug, we're iterating a lot right now in both this repo and the atlas-app-toolkit repo that houses many of these utility functions, so sorry about the instability. I'll check into this tomorrow if nobody else gets to it first.

**Comment by dmacthedestroyer** [comment]
hi @majelbstoat, thanks for the feedback! Could you provide more information?

It looks like we broke the api in the app toolkit yesterday with [this commit](https://github.com/infobloxopen/atlas-app-toolkit/commit/286a0d8a6816d1ed18e53d87b630c5e93adc6a02#diff-62ccadf212d9cd579f8b8c86400f2c81), and updated the protoc-gen-gorm repo accordingly yesterday with [this commit](https://github.com/infobloxopen/protoc-gen-gorm/commit/5b0e2ce3f7c493f15daec42c53c782207f0c39d2)

My guess is if you update both your protoc-gen-gorm binary as well as update your dependency to atlas-app-toolkit, you should be good to go.

**Comment by majelbstoat** [comment]
👍🏼 I’ll pull the latest versions and check back.

**Comment by Calebjh** [comment]
Hey @majelbstoat, any update for if this was just a version mismatch and can be closed?

**Comment by majelbstoat** [comment]
I won't be able to check for a couple of days I'm afraid. It does sound likely though, so feel free to optimistically close and I'll update if it turns out not to be the case.

**Comment by Calebjh** [comment]
Closing optimistically.
